/* Auto-generated by tools/dataemit.py — do not edit. */
#include "data_pool.h"

const unsigned char g_a5_init_bytes[1] = {
    0,    /* stub — no FRUA resource fork was available */
};

const g_a5_reloc_t g_a5_relocs[1] = {
    { 0, G_A5_RELOC_A5 },    /* stub — no FRUA resource fork was available */
};
