/*
 * THINK C DATA + DREL replay — engine startup.
 *
 * The Mac runtime, on launch, sets up the A5 world by:
 *   1. allocating the below-A5 region (data + bss, sized via CODE 0
 *      header bytes),
 *   2. zero-filling it,
 *   3. copying the DATA resource into the top of that region (DATA
 *      ends one byte before A5),
 *   4. walking the DREL resource, adding the A5 base address to each
 *      A5-base pointer slot and the A4 base address (the STRS pool)
 *      to each A4-base pointer slot.
 *
 * `data_pool_replay()` reproduces that flow on the Atari side. The
 * below-A5 region lives in a statically-allocated 32 KB buffer
 * (slightly above the deepest reloc the FRUA build references at
 * -20096); A5 is conceptually the address just past the last byte
 * (`g_a5_below + A5_BELOW_SIZE`). All offsets in the reloc table are
 * negative relative to that address.
 *
 * TWO SOURCES for the DATA + DREL tables:
 *   - Compiled in (`data_pool.c`, generated by tools/dataemit.py from
 *     frua.rsc at BUILD time) — the dev path. Those ~31 KB are
 *     copyrighted FRUA bytes, so a binary built this way is NOT
 *     redistributable.
 *   - Loaded from frua.rsc at RUNTIME (dp_replay_runtime, below) —
 *     used whenever the compiled pool is a stub. The C decoder mirrors
 *     tools/datapool.py: expand the compressed DATA with the ZERO
 *     run-length table, then apply the DREL words. This lets us ship a
 *     STUB build that carries zero copyrighted bytes and reconstructs
 *     the A5 world from the user's own frua.rsc at launch.
 *
 * Lifted globals are still scattered file-level statics across boot.c;
 * the replay populates a SEPARATE buffer accessible via `g_a5_at()`.
 * Migrating individual lifts to read from the replay buffer is a
 * gradual job — the replay infrastructure landing first lets future
 * lifts pull initial values from FRUA's actual DATA pool one cluster
 * at a time.
 */

#include <stddef.h>
#include <string.h>

#include "data_pool.h"
#include "data_pool_replay.h"
#include "data_pool_decode.h" /* dp_expand, dp_drel_word (host-tested) */
#include "str.h"             /* ua_strs_at */
#include "macmemory.h"       /* Handle */
#include "resources.h"       /* GetResource, SizeResource */
#include "dbglog.h"

/* Four-character resource codes (as ResType longs). */
#define RSRC_DATA 0x44415441L   /* 'DATA' — compressed A5-below image   */
#define RSRC_ZERO 0x5A45524FL   /* 'ZERO' — DATA zero-run length table   */
#define RSRC_DREL 0x4452454CL   /* 'DREL' — A5/A4 pointer relocations     */

unsigned char g_a5_below[A5_BELOW_SIZE];

/* The conceptual A5 base — the byte address just past the last byte
 * of g_a5_below. Reads `g_a5_at(-N)` resolve to g_a5_below[A5_BELOW_SIZE
 * - N]. */
void *g_a5_below_base(void)
{
	return (void *)(g_a5_below + A5_BELOW_SIZE);
}

void *g_a5_at(int offset)
{
	long pos = (long)A5_BELOW_SIZE + offset;

	if (pos < 0 || pos >= (long)A5_BELOW_SIZE)
		return NULL;
	return (void *)(g_a5_below + pos);
}

/* Add `base` to the 4-byte slot at A5 offset `off`, bounds-checked. */
static void dp_reloc_slot(short off, long base)
{
	long pos = (long)A5_BELOW_SIZE + off;

	if (pos < 0 || pos + 4 > (long)A5_BELOW_SIZE)
		return;
	*(long *)(g_a5_below + pos) += base;
}

/* Apply the compiled-in reloc table (dev build). */
static void dp_apply_compiled(void)
{
	long a5base = (long)(unsigned long)g_a5_below_base();
	long a4base = (long)(unsigned long)ua_strs_at(0);
	int  i;

	memcpy(g_a5_below + A5_BELOW_SIZE - G_A5_INIT_BYTES_LEN,
	       g_a5_init_bytes, G_A5_INIT_BYTES_LEN);
	for (i = 0; i < G_A5_RELOCS_COUNT; i++) {
		if (g_a5_relocs[i].base == G_A5_RELOC_A5)
			dp_reloc_slot(g_a5_relocs[i].a5_offset, a5base);
		else if (g_a5_relocs[i].base == G_A5_RELOC_A4)
			dp_reloc_slot(g_a5_relocs[i].a5_offset, a4base);
	}
	dbg_log_num("data_pool: replayed bytes = ", (long)G_A5_INIT_BYTES_LEN);
	dbg_log_num("data_pool: relocs applied = ", (long)G_A5_RELOCS_COUNT);
}

/*
 * Runtime replay: reconstruct the A5 world from frua.rsc's DATA / ZERO
 * / DREL resources (no copyrighted bytes in the binary). Returns 1 on
 * success, 0 if the resources aren't present or don't decode.
 */
static int dp_replay_runtime(void)
{
	Handle hd = GetResource(RSRC_DATA, 0);
	Handle hz = GetResource(RSRC_ZERO, 0);
	Handle hr = GetResource(RSRC_DREL, 0);
	const unsigned char *data, *zero, *drel;
	long dlen, zlen, rlen, L, a5base, a4base, i;

	if (hd == NULL || *hd == NULL || hz == NULL || *hz == NULL ||
	    hr == NULL || *hr == NULL)
		return 0;
	data = (const unsigned char *)*hd; dlen = SizeResource(hd);
	zero = (const unsigned char *)*hz; zlen = SizeResource(hz);
	drel = (const unsigned char *)*hr; rlen = SizeResource(hr);

	/* Pass 1: measure. Pass 2: expand into the TOP of the buffer so the
	 * last DATA byte lands one byte before A5. */
	L = dp_expand(data, dlen, zero, zlen, NULL);
	if (L <= 0 || L > (long)A5_BELOW_SIZE) {
		dbg_log_num("data_pool: runtime expand out of range = ", L);
		return 0;
	}
	if (dp_expand(data, dlen, zero, zlen,
	              g_a5_below + A5_BELOW_SIZE - L) != L)
		return 0;

	/* Apply DREL straight from the word stream: bit 0 selects the base
	 * (1 = A4/STRS, 0 = A5), bits 15..1 are the even signed offset. */
	a5base = (long)(unsigned long)g_a5_below_base();
	a4base = (long)(unsigned long)ua_strs_at(0);
	for (i = 0; i + 2 <= rlen; i += 2) {
		unsigned short w = ((unsigned short)drel[i] << 8) | drel[i + 1];
		short off;
		int   is_a4 = dp_drel_word(w, &off);

		dp_reloc_slot(off, is_a4 ? a4base : a5base);
	}
	dbg_log_num("data_pool: runtime replay bytes = ", L);
	dbg_log_num("data_pool: runtime relocs = ", rlen / 2);
	return 1;
}

void data_pool_replay(void)
{
	/* Step 1 — zero the buffer (matches the Mac's BSS init). */
	memset(g_a5_below, 0, sizeof g_a5_below);

	if (G_A5_INIT_BYTES_LEN > 0 && G_A5_RELOCS_COUNT > 0) {
		dp_apply_compiled();		/* dev build: pool compiled in  */
		return;
	}
	if (dp_replay_runtime())		/* shipping build: from frua.rsc */
		return;
	dbg_log("data_pool: no compiled pool and no runtime DATA/DREL");
}
