/* Auto-generated by tools/dataemit.py — do not edit. */
#ifndef ENGINE_DATA_POOL_H
#define ENGINE_DATA_POOL_H

#define G_A5_INIT_BYTES_LEN 0
#define G_A5_RELOCS_COUNT   0

/* The initialised below-A5 image: byte 0 is at A5 - G_A5_INIT_BYTES_LEN. */
extern const unsigned char g_a5_init_bytes[1];

/* DREL relocations to apply after copying g_a5_init_bytes into the
 * below-A5 buffer. `a5_offset` is the signed byte offset of a 4-byte
 * slot; `base` is 0 = A5 (below-A5 buffer) or 1 = A4 (STRS pool). */
typedef struct g_a5_reloc { short a5_offset; unsigned char base; } g_a5_reloc_t;
#define G_A5_RELOC_A5 0
#define G_A5_RELOC_A4 1
extern const g_a5_reloc_t g_a5_relocs[1];

#endif /* ENGINE_DATA_POOL_H */
