#!/usr/bin/env python3
"""Extract the A4 (STRS) pointer map from the Mac DATA + DREL resources.

WHY: 1016 of the A5 world's pointer slots hold addresses into the STRS string
pool. The Mac runtime materialises them at load time — the DATA image stores a
raw STRS *offset* in each slot and DREL says "add the A4 (STRS) base to this
slot". `data_pool_replay()` reproduces that. To retire the replay (#67,
ADR-0017) the port must know the same thing without the DATA resource, and it
turns out that is mechanical rather than a hand-reconstruction grind:

    DREL  -> which slots are A4-based (bit 0 set) and their A5-relative offsets
    DATA  -> the value sitting in each of those slots = the STRS offset

So the whole A4 half of the A5 world is recoverable as a table of integer
pairs. This emits it.

WHAT SHIPS. The table is `(a5_slot, strs_offset)` — **positions only, never
text**, the same shape ADR-0017 already ratifies for the DOS string map. The
strings themselves come from the user's own STRS (Mac) or CKIT.EXE (DOS) at
runtime; this only records where each global points.

Verified: slot -13448 -> STRS+8954 = "Boots", the string whose absence sent the
no-replay boot into the copy-protection challenge (commit a406adc).

Usage:
    python3 tools/a4map.py <rfork> --emit-c src/engine/a4_map.c
    python3 tools/a4map.py <rfork> --list | head
"""
import argparse
import struct
import sys


def parse_a4_map(img, drel):
    """[(a5_slot_offset, strs_offset)] for every A4-based DREL relocation.

    `img` is the expanded DATA image (its length is the A5 base; slots are
    negative offsets from there). A DREL word has bit 0 set for A4/STRS and
    bits 15..1 as the even signed slot offset.
    """
    a5_base = len(img)
    out = []
    for i in range(0, len(drel) - 1, 2):
        w = (drel[i] << 8) | drel[i + 1]
        if not (w & 1):                     # 0 = A5-internal, not ours
            continue
        off = w & 0xFFFE
        if off >= 0x8000:
            off -= 0x10000
        p = a5_base + off
        if 0 <= p + 4 <= len(img):
            out.append((off, struct.unpack(">I", img[p:p + 4])[0]))
    return out


def parse_a5_internal(img, drel):
    """[(slot, target)] for A5-based (bit 0 clear) relocations.

    These point at other A5-world locations rather than into STRS. Only the
    ones whose target is BELOW A5 are returned: the port models the below-A5
    region as g_a5_below[] and has no above-A5 area, so a slot pointing above
    A5 cannot be materialised (7 of the 10 in the FRUA build do — they are
    reported separately by the caller).
    """
    a5_base = len(img)
    below, above = [], []
    for i in range(0, len(drel) - 1, 2):
        w = (drel[i] << 8) | drel[i + 1]
        if w & 1:
            continue
        off = w & 0xFFFE
        if off >= 0x8000:
            off -= 0x10000
        p = a5_base + off
        if not (0 <= p + 4 <= len(img)):
            continue
        v = struct.unpack(">I", img[p:p + 4])[0]
        target = v - (1 << 32) if v >= (1 << 31) else v
        (below if -a5_base <= target < 0 else above).append((off, target))
    return below, above


def load(path):
    sys.path.insert(0, __file__.rsplit("/", 1)[0])
    from macrsrc import ResourceFork
    import datapool
    rf = ResourceFork.from_file(path)
    res = {(r.type, r.id): r.data for r in rf.resources}
    img = datapool.expand_data(res[("DATA", 0)], res[("ZERO", 0)])
    return img, res[("DREL", 0)], res[("STRS", 0)]


def emit_c(pairs, strs, fh):
    fh.write("/* GENERATED by tools/a4map.py — do not edit.\n"
             " *\n"
             " * The A4 (STRS) pointer slots of the A5 world: each entry says\n"
             " * \"global at A5-offset `slot` points at STRS+`off`\". Positions\n"
             " * only — the text lives in the user's own string pool. See\n"
             " * ADR-0017 and docs/dos-strings-probe.md.\n"
             " */\n"
             "#include \"a4_map.h\"\n\n"
             "const struct a4_slot g_a4_map[] = {\n")
    for slot, off in pairs:
        end = strs.find(b"\x00", off)
        text = strs[off:end if end >= 0 else off + 16]
        try:
            note = text.decode("mac-roman")[:28]
        except Exception:
            note = ""
        note = "".join(c if 32 <= ord(c) < 127 else "." for c in note)
        fh.write(f"\t{{ {slot:7d}, {off:6d} }},  /* {note} */\n")
    fh.write("};\n\n"
             f"const short g_a4_map_count = {len(pairs)};\n")


def emit_c_internal(below, above, fh):
    """The A5-internal half: slots pointing at other A5-world locations."""
    fh.write("\n/* A5-internal relocations — slots pointing at other A5-world\n"
             " * locations rather than into STRS. Only below-A5 targets are\n"
             f" * emitted; {len(above)} point ABOVE A5, a region the port does not\n"
             " * model (g_a5_below[] is below-A5 only), so they cannot be\n"
             " * materialised. Listed here so the gap is on the record:\n")
    for slot, target in above:
        fh.write(f" *   g_a5_long({slot:7d}) = A5+{target}\n")
    fh.write(" */\n"
             "const struct a4_slot g_a5int_map[] = {\n")
    for slot, target in below:
        fh.write(f"\t{{ {slot:7d}, {target:6d} }},\n")
    fh.write("};\n\n"
             f"const short g_a5int_map_count = {len(below)};\n")


def scalar_runs(img, drel):
    """[(a5_slot, bytes)] — non-zero DATA bytes NOT covered by a relocation.

    DIAGNOSTIC ONLY. These are raw initialised values copied out of the Mac
    application, i.e. the same copyrighted payload data_pool.c carries; unlike
    the position tables they must NOT ship in a redistributable build. They
    exist so the scalar half can be bisected — seed them, confirm parity, then
    narrow to the slots a symptom actually needs and port-author those.
    """
    a5_base = len(img)
    covered = bytearray(a5_base)
    below, above = parse_a5_internal(img, drel)
    for slot, _ in parse_a4_map(img, drel) + below + above:
        p = a5_base + slot
        for k in range(4):
            if 0 <= p + k < a5_base:
                covered[p + k] = 1

    runs, start = [], None
    for i in range(a5_base + 1):
        hot = i < a5_base and img[i] != 0 and not covered[i]
        if hot and start is None:
            start = i
        elif not hot and start is not None:
            runs.append((start - a5_base, bytes(img[start:i])))
            start = None
    return runs


def referenced_offsets(paths):
    """A5 offsets the lifted C actually names, via the g_a5_* accessors.

    Catches `g_a5_long(-1234)` / `g_a5_byte(-1234)` / ... and the bare
    `g_a5_1234` macro spelling. It cannot see indirect access — code that
    takes the address of a slot and walks past it, or memcpys a struct — so a
    scalar set filtered by this is a LOWER BOUND on what is needed. Verify
    parity after filtering rather than assuming it holds.
    """
    import re
    pat_call = re.compile(r"g_a5_(?:byte|word|long|ptr|buf|chars|shorts|longs)"
                          r"\(\s*-(\d+)")
    pat_macro = re.compile(r"\bg_a5_(\d+)\b")
    out = set()
    for p in paths:
        with open(p) as fh:
            src = fh.read()
        out |= {int(m) for m in pat_call.findall(src)}
        out |= {int(m) for m in pat_macro.findall(src)}
    return out


def filter_runs_to_refs(runs, refs, gap=4):
    """Keep WHOLE runs belonging to a referenced structure.

    The old version kept only runs overlapping a referenced offset within a
    4-byte window. That silently dropped indexed tables: a base like
    g_a5_27980 is named once and read as g_a5_27980[i], so only its first 4
    bytes fell in the window and the rest was lost — the compass direction
    table (#73) was exactly this. A "lower bound" that hides needed data.

    Instead, group runs into clusters (consecutive runs separated by <= `gap`
    zero bytes — the interior padding of a table) and keep every run of any
    cluster that contains a referenced offset. So one reference to a table's
    base pulls in the whole table.
    """
    runs = sorted(runs)
    refset = set(-o for o in refs)          # refs are positive; slots negative
    clusters, cur = [], []
    for slot, b in runs:
        if cur and slot - (cur[-1][0] + len(cur[-1][1])) > gap:
            clusters.append(cur)
            cur = []
        cur.append((slot, b))
    if cur:
        clusters.append(cur)

    keep = []
    for cl in clusters:
        lo = cl[0][0]
        hi = cl[-1][0] + len(cl[-1][1])
        if any(lo <= rs < hi for rs in refset):
            keep.extend(cl)
    return keep


def coalesce_runs_by_dos(runs, dos, max_gap=32, min_merge=8, max_len=1024):
    """Merge zero-split fragments back into whole tables the DOS binary holds.

    scalar_runs() breaks at every zero byte, so a table with interior zeros
    shreds into fragments — most shorter than split_by_dos's min_run, so they
    landed in the hand-authoring residue even though the WHOLE table sits
    verbatim in CKIT.EXE. The -27848 terrain descriptor table was the proof:
    70 four-byte entries, 40 of them zero-damaged in a no-replay build (#75,
    the combat-map wall chunks), yet the full 280-byte region is contiguous in
    the DOS executable.

    So: cluster neighbouring runs (interior gaps <= max_gap zero bytes),
    and where the ENTIRE region — zeros included — occurs verbatim in the DOS
    image, emit it as ONE run. A region that doesn't match (or exceeds
    max_len, the runtime's DOS_RUN_MAX) splits at its widest interior gap and
    each half retries. Single leftover runs pass through untouched for
    split_by_dos's usual handling. min_merge keeps chance matches out: a
    merged region must be at least that long to count.

    Interior zeros are copied by the runtime as zeros (a no-op on a zeroed
    world), and dos_scalars_load applies per-byte only where the A5 world is
    still zero, so a merged region can safely overlap authored scalars.
    """
    runs = sorted(runs)
    out = []

    def region(cl):
        slot = cl[0][0]
        end = cl[-1][0] + len(cl[-1][1])
        b = bytearray(end - slot)
        for s, rb in cl:
            b[s - slot:s - slot + len(rb)] = rb
        return slot, bytes(b)

    def emit(cl):
        if len(cl) == 1:
            out.append(cl[0])
            return
        slot, b = region(cl)
        if min_merge <= len(b) <= max_len and dos.find(b) >= 0:
            out.append((slot, b))
            return
        gaps = [(cl[i + 1][0] - (cl[i][0] + len(cl[i][1])), i)
                for i in range(len(cl) - 1)]
        _, i = max(gaps)
        emit(cl[:i + 1])
        emit(cl[i + 1:])

    cur = []
    for slot, b in runs:
        if cur and slot - (cur[-1][0] + len(cur[-1][1])) > max_gap:
            emit(cur)
            cur = []
        cur.append((slot, b))
    if cur:
        emit(cur)
    return out


def split_by_dos(runs, dos, min_run=4):
    """(locatable, residue) — which scalar runs live in the DOS executable.

    The big scalar runs are game-rule tables, and FRUA is the same game on both
    platforms, so most of them are byte-identical in CKIT.EXE. Those can be
    extracted from the user's own DOS binary exactly as the string pool is
    (docs/dos-strings-probe.md), which keeps them out of our source entirely.

    Runs shorter than `min_run` are treated as residue regardless: a 1-3 byte
    sequence matches somewhere by chance, so a "hit" would not identify
    anything. They are small (flags, counts, defaults) and are the natural
    port-authoring set.

    A run occurring at several DOS offsets is still fine — the bytes are
    identical, so any occurrence serves.
    """
    locatable, residue = [], []
    for slot, b in runs:
        if len(b) < min_run:
            residue.append((slot, b))
            continue
        i = dos.find(b)
        (locatable.append((slot, b, i)) if i >= 0
         else residue.append((slot, b)))
    return locatable, residue


def emit_c_dos_scalars(locatable, fh):
    fh.write("\n/* Scalar runs recoverable from the user's DOS CKIT.EXE:\n"
             " * \"the A5 global at `slot` is `len` bytes taken from DOS+`off`\".\n"
             " * Shared game-rule tables, byte-identical between the releases.\n"
             " * Positions and a checksum only — no values — so this ships.\n"
             " *\n"
             " * `sum` is the 16-bit sum of the run's bytes. ADR-0017 requires\n"
             " * install-time verification rather than trusting offsets: a\n"
             " * repacked or different build shifts every offset, and reading\n"
             " * from the wrong place would silently poison the A5 world. A\n"
             " * checksum catches that without carrying the values themselves.\n"
             " */\n"
             "const struct a4_dos_run g_a5_dos_scalars[] = {\n")
    for slot, b, off in locatable:
        chk = sum(b) & 0xFFFF
        fh.write(f"\t{{ {slot:7d}, {len(b):4d}, {off:7d}L, 0x{chk:04x} }},\n")
    fh.write("};\n\n"
             f"const short g_a5_dos_scalar_count = {len(locatable)};\n")


def emit_c_scalars(runs, fh):
    blob = b"".join(b for _, b in runs)
    fh.write("\n/* DIAGNOSTIC ONLY — raw initialised values from the Mac DATA\n"
             " * image that no relocation covers. This is copyrighted payload,\n"
             " * the same kind data_pool.c carries: it must NOT ship in a\n"
             " * redistributable build. Present so the scalar half of the A5\n"
             " * world can be bisected (seed, confirm parity, then narrow to\n"
             " * what a symptom needs and port-author those slots properly).\n"
             " */\n"
             "const unsigned char g_a5_scalar_blob[] = {\n")
    for i in range(0, len(blob), 16):
        fh.write("\t" + "".join(f"0x{c:02x}," for c in blob[i:i + 16]) + "\n")
    fh.write("};\n\nconst struct a4_run g_a5_scalar_runs[] = {\n")
    pos = 0
    for slot, b in runs:
        fh.write(f"\t{{ {slot:7d}, {len(b):4d}, {pos:6d} }},\n")
        pos += len(b)
    fh.write("};\n\n"
             f"const short g_a5_scalar_run_count = {len(runs)};\n")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("rfork", nargs="?", help="Mac application resource fork")
    ap.add_argument("--emit-c", metavar="FILE", help="write the C table")
    ap.add_argument("--list", action="store_true", help="print slot -> string")
    ap.add_argument("--stub", action="store_true",
                    help="emit empty tables (no resource fork available)")
    ap.add_argument("--with-scalars", action="store_true",
                    help="DIAGNOSTIC: also emit the raw scalar blob "
                         "(copyrighted payload — never ship this)")
    ap.add_argument("--dos", metavar="CKIT.EXE",
                    help="split scalars into DOS-extractable vs residue")
    ap.add_argument("--residue-report", metavar="FILE",
                    help="write the hand-authoring worklist (with --dos)")
    ap.add_argument("--refs-from", metavar="SRC", action="append", default=[],
                    help="restrict scalars to slots this source names "
                         "(repeatable); a LOWER BOUND, verify parity")
    args = ap.parse_args(argv)

    if args.stub:
        if not args.emit_c:
            ap.error("--stub requires --emit-c")
        with open(args.emit_c, "w") as fh:
            emit_c([], b"", fh)
            emit_c_internal([], [], fh)
            emit_c_dos_scalars([], fh)
            if args.with_scalars:
                emit_c_scalars([], fh)
        print(f"a4_map: STUBBED (no resource fork) -> {args.emit_c}",
              file=sys.stderr)
        return 0
    if not args.rfork:
        ap.error("rfork is required unless --stub is given")

    img, drel, strs = load(args.rfork)
    pairs = parse_a4_map(img, drel)
    print(f"A4 (STRS) slots: {len(pairs)}", file=sys.stderr)

    if args.list:
        for slot, off in pairs:
            end = strs.find(b"\x00", off)
            print(f"  g_a5_long({slot:7d}) -> STRS+{off:<6d} {strs[off:end]!r}")
    below, above = parse_a5_internal(img, drel)
    print(f"A5-internal slots: {len(below)} below-A5 (usable), "
          f"{len(above)} above-A5 (cannot be modelled)", file=sys.stderr)

    if args.emit_c:
        with open(args.emit_c, "w") as fh:
            emit_c(pairs, strs, fh)
            emit_c_internal(below, above, fh)

            # The FULL run set drives everything shippable. The --refs-from
            # filter is NOT applied to shipped output any more: it was a lower
            # bound that hid indirectly-indexed tables (#73). It survives only
            # to annotate the residue report with the reference-reachable set.
            runs = scalar_runs(img, drel)
            allb = sum(len(b) for _, b in runs)

            # DOS scalar map — positions + checksum only, no values, so it
            # SHIPS. Because positions are free, emit EVERY DOS-extractable
            # run, unfiltered: this auto-closes indexed-table gaps (the table
            # lives in the user's own binary) with no per-table authoring.
            loc, res = [], runs
            if args.dos:
                dosimg = open(args.dos, "rb").read()
                # Re-fuse zero-split tables first (#75): fragments whose whole
                # region matches the DOS image become one run each.
                loc, res = split_by_dos(
                    coalesce_runs_by_dos(runs, dosimg), dosimg)
                lb = sum(len(b) for _, b, _ in loc)
                rb = sum(len(b) for _, b in res)
                print(f"  DOS-extractable (ALL, shipped): {len(loc)} runs / "
                      f"{lb} bytes; residue to author: {len(res)} runs / "
                      f"{rb} bytes ({100*rb/(lb+rb):.1f}%)", file=sys.stderr)
                if args.residue_report:
                    reached = set()
                    if args.refs_from:
                        refs = referenced_offsets(args.refs_from)
                        reached = {s for s, _ in
                                   filter_runs_to_refs(res, refs)}
                    with open(args.residue_report, "w") as rf2:
                        rf2.write("# A5 scalar residue — port-author these\n")
                        rf2.write("# Not recoverable from the DOS binary "
                                  "(absent, or too short to locate).\n")
                        rf2.write("# [R] = reference-reachable (a named offset "
                                  "lands in its cluster); the rest are\n")
                        rf2.write("# indirectly-indexed and just as needed — "
                                  "the compass table (#73) was one.\n")
                        rf2.write(f"# {len(res)} runs, {rb} bytes\n\n")
                        for slot, b in sorted(res, key=lambda x: -len(x[1])):
                            tag = "R" if slot in reached else " "
                            rf2.write(f"[{tag}] A5{slot:<8} len {len(b):<4} "
                                      f"{b.hex(' ')}\n")
                    print(f"  residue worklist -> {args.residue_report}",
                          file=sys.stderr)
            emit_c_dos_scalars(loc, fh)

            # Diagnostic blob (FRUA_SCALAR_SEED) — the FULL set, so it can
            # reproduce the whole A5 world for parity testing. Copyrighted;
            # never in a release.
            if args.with_scalars:
                emit_c_scalars(runs, fh)
                print(f"  + {len(runs)} scalar runs "
                      f"({sum(len(b) for _, b in runs)} bytes) [DIAGNOSTIC]",
                      file=sys.stderr)
        print(f"wrote {len(pairs)} A4 + {len(below)} A5-internal entries "
              f"-> {args.emit_c}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
