"""Scan a FRSC archive for DATA / DREL and emit a C replay table.

Reads `frua.rsrc` (the FRSC archive `tools/rsrcpack.py` builds from
the Mac resource fork), pulls out the `DATA` and `DREL` resources,
runs them through `datapool.py`, and writes a small C header to
stdout (or a path) that the engine-startup replay can ingest:

  - `g_a5_init_bytes[]` — every initialised A5-relative slot the
    THINK C runtime would have copied into the below-A5 region.
  - `g_a5_relocs[]` — the (offset, base) pairs the runtime applies
    after the copy, so pointer slots end up holding absolute
    addresses into either the A5 world (g_a5_below pointer) or the
    STRS pool (`ua_strs_at(0)`).

Usage:
    python3 tools/dataemit.py [frua.rsrc] [--out path] [--summary]
"""

import argparse
import struct
import sys
from pathlib import Path

# Add tools/ to path so datapool imports cleanly when run directly.
sys.path.insert(0, str(Path(__file__).resolve().parent))

from datapool import (                                                  # noqa: E402
    RELOC_BASE_A4,
    RELOC_BASE_A5,
    parse_data,
    parse_drel,
)


def _frsc_lookup(blob: bytes, want_type: bytes, want_id: int = 0) -> bytes:
    """Pull a single resource's data from a FRSC archive."""
    magic = blob[:4]
    if magic != b"FRSC":
        raise ValueError("not a FRSC archive (magic %r)" % magic)
    count, tbl_off = struct.unpack_from(">HI", blob, 6)
    for i in range(count):
        e = tbl_off + i * 16
        rtype = blob[e:e + 4]
        rid, _attrs, off, length = struct.unpack_from(">hHII", blob, e + 4)
        if rtype == want_type and rid == want_id:
            return blob[off:off + length]
    raise KeyError((want_type.decode(), want_id))


def emit_c_header(data_bytes: bytes, table, out) -> None:
    """Emit a C header from parsed DATA + DREL.

    `table` is the RelocTable returned by parse_drel.
    """
    # ISO C forbids 0-length arrays; clamp to 1 and rely on the LEN /
    # COUNT macros to gate any access.
    arr_len   = max(len(data_bytes), 1)
    relocs_n  = max(len(table.entries), 1)
    print("/* Auto-generated by tools/dataemit.py — do not edit. */", file=out)
    print("#ifndef ENGINE_DATA_POOL_H", file=out)
    print("#define ENGINE_DATA_POOL_H", file=out)
    print("", file=out)
    print(f"#define G_A5_INIT_BYTES_LEN {len(data_bytes)}", file=out)
    print(f"#define G_A5_RELOCS_COUNT   {len(table.entries)}", file=out)
    print("", file=out)
    print("/* The initialised below-A5 image: byte 0 is at A5 - "
          "G_A5_INIT_BYTES_LEN. */", file=out)
    print(f"extern const unsigned char g_a5_init_bytes[{arr_len}];", file=out)
    print("", file=out)
    print("/* DREL relocations to apply after copying g_a5_init_bytes into the\n"
          " * below-A5 buffer. `a5_offset` is the signed byte offset of a 4-byte\n"
          " * slot; `base` is 0 = A5 (below-A5 buffer) or 1 = A4 (STRS pool). */",
          file=out)
    print("typedef struct g_a5_reloc { short a5_offset; "
          "unsigned char base; } g_a5_reloc_t;", file=out)
    print("#define G_A5_RELOC_A5 0", file=out)
    print("#define G_A5_RELOC_A4 1", file=out)
    print(f"extern const g_a5_reloc_t g_a5_relocs[{relocs_n}];", file=out)
    print("", file=out)
    print("#endif /* ENGINE_DATA_POOL_H */", file=out)


def emit_c_source(data_bytes: bytes, table, out) -> None:
    """Emit the matching C source file with the literal arrays."""
    arr_len  = max(len(data_bytes), 1)
    relocs_n = max(len(table.entries), 1)

    print('/* Auto-generated by tools/dataemit.py — do not edit. */', file=out)
    print('#include "data_pool.h"', file=out)
    print("", file=out)
    print(f"const unsigned char g_a5_init_bytes[{arr_len}] = {{", file=out)
    if data_bytes:
        # 16 bytes per line.
        for i in range(0, len(data_bytes), 16):
            row = data_bytes[i:i + 16]
            cells = ", ".join(f"0x{b:02x}" for b in row)
            print(f"    {cells},", file=out)
    else:
        print("    0,    /* stub — no FRUA resource fork was available */",
              file=out)
    print("};", file=out)
    print("", file=out)
    print(f"const g_a5_reloc_t g_a5_relocs[{relocs_n}] = {{", file=out)
    if table.entries:
        for entry in table.entries:
            base_id = "G_A5_RELOC_A5" if entry.base == RELOC_BASE_A5 \
                                       else "G_A5_RELOC_A4"
            print(f"    {{ {entry.a5_offset:6d}, {base_id} }},", file=out)
    else:
        print("    { 0, G_A5_RELOC_A5 },"
              "    /* stub — no FRUA resource fork was available */",
              file=out)
    print("};", file=out)


def summary(data_bytes: bytes, table, out) -> None:
    print(f"DATA: {len(data_bytes)} bytes", file=out)
    print(f"DREL: {len(table.entries)} entries "
          f"({sum(1 for e in table.entries if e.base == RELOC_BASE_A5)} A5, "
          f"{sum(1 for e in table.entries if e.base == RELOC_BASE_A4)} A4)",
          file=out)
    a5s = [e.a5_offset for e in table.entries if e.base == RELOC_BASE_A5]
    if a5s:
        print(f"A5 offset range: [{min(a5s)}, {max(a5s)}]", file=out)
    a4s = [e.a5_offset for e in table.entries if e.base == RELOC_BASE_A4]
    if a4s:
        print(f"A4 offset range: [{min(a4s)}, {max(a4s)}]", file=out)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("archive", nargs="?", default="frua.rsrc",
                    help="FRSC archive path (default: frua.rsrc)")
    ap.add_argument("--out-h", help="emit C header here (default: stdout)")
    ap.add_argument("--out-c", help="emit C source here")
    ap.add_argument("--summary", action="store_true",
                    help="print summary to stderr")
    ap.add_argument("--stub", action="store_true",
                    help="emit empty (zero-entry) tables — for builds "
                         "without the FRUA resource fork")
    args = ap.parse_args(argv)

    if args.stub:
        data_bytes = b""
        drel_bytes = b""
    else:
        blob = Path(args.archive).read_bytes()
        data_bytes = _frsc_lookup(blob, b"DATA", 0)
        drel_bytes = _frsc_lookup(blob, b"DREL", 0)
    table = parse_drel(drel_bytes)
    pool = parse_data(data_bytes, drel_min_a5_offset=table.a5_min())

    if args.summary:
        summary(pool.bytes, table, sys.stderr)

    if args.out_h:
        with open(args.out_h, "w") as f:
            emit_c_header(pool.bytes, table, f)
    if args.out_c:
        with open(args.out_c, "w") as f:
            emit_c_source(pool.bytes, table, f)
    if not args.out_h and not args.out_c:
        # Default: header to stdout.
        emit_c_header(pool.bytes, table, sys.stdout)


if __name__ == "__main__":
    main()
