#!/usr/bin/env python3
"""Generate installer/strs_map_dos12.h — the C form of the STRS positions map.

The native installer (installer/rsrc_from_dos.c) rebuilds frua.rsc from the
user's own CKIT.EXE on the Atari/Amiga itself, so it needs the same table
tools/rsrc_from_dos.py reads from installer/strs_map_dos12.json. Parsing JSON
on a 68000 is not worth it; this emits the table as C arrays at build time,
exactly the way src/engine/a4_map.c is generated.

★ THE AUTHORED STRINGS ARE IMPORTED, NOT RETYPED. rsrc_from_dos.py owns the 37
port-authored Mac-only entries (ADR-0017 decision 6) and the engine compares
against them byte-for-byte — two hand-maintained copies would diverge silently
and the divergence would only show as a wrong filename or a missing prompt at
runtime. Importing makes that impossible, and tests/test_rsrc_from_dos_c.py
byte-compares the C output against the Python one over the real executable.

POSITIONS ONLY, never text: the emitted table is offsets and lengths into the
user's own executable, so a build carrying it is still redistributable. The
authored strings are port-authored, not extracted, which is what makes them
safe to embed.

    python3 tools/gen_strs_map_h.py [-o installer/strs_map_dos12.h]
"""
import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import rsrc_from_dos                                    # noqa: E402  (path set above)


def c_bytes(b):
    return ", ".join(str(x) for x in b)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("-o", "--out", default=os.path.join(HERE, os.pardir,
                    "installer", "strs_map_dos12.h"))
    ap.add_argument("--map", default=rsrc_from_dos.DEFAULT_MAP)
    args = ap.parse_args(argv)

    with open(args.map) as fh:
        doc = json.load(fh)

    ents = sorted((int(k), v[0], v[1]) for k, v in doc["entries"].items())
    authored = sorted(rsrc_from_dos.AUTHORED.items())
    sha = bytes.fromhex(doc["ckit_sha256"])
    assert len(sha) == 32, sha

    # Widths are asserted, not assumed: if a future map exceeds them the build
    # fails here rather than silently truncating an offset at runtime.
    assert max(e[0] for e in ents) < 0x10000, "pool offset needs more than u16"
    assert max(e[2] for e in ents) < 0x100, "entry length needs more than u8"
    assert max(a[0] for a in authored) < 0x10000, "authored offset > u16"

    o = []
    o.append("/* GENERATED by tools/gen_strs_map_h.py — do not edit. */")
    o.append("/* Positions into the user's own CKIT.EXE, plus the port-authored")
    o.append(" * Mac-only strings. No extracted game text. See ADR-0017. */")
    o.append("#ifndef STRS_MAP_DOS12_H")
    o.append("#define STRS_MAP_DOS12_H")
    o.append("")
    o.append(f"#define SM_POOL_SIZE  {doc['pool_size']}L")
    o.append(f"#define SM_CKIT_SIZE  {doc['ckit_size']}L")
    o.append(f"#define SM_NENTRIES   {len(ents)}")
    o.append(f"#define SM_NAUTHORED  {len(authored)}")
    o.append("")
    o.append("static const unsigned char sm_ckit_sha256[32] = {")
    o.append("\t" + c_bytes(sha))
    o.append("};")
    o.append("")
    # Three parallel arrays rather than a struct: a struct of {u16,u32,u8} pads
    # to 8 bytes on both compilers and would cost ~2 KB of nothing.
    o.append("static const unsigned short sm_pool_off[SM_NENTRIES] = {")
    for i in range(0, len(ents), 16):
        o.append("\t" + ", ".join(str(e[0]) for e in ents[i:i + 16]) + ",")
    o.append("};")
    o.append("static const unsigned long sm_dos_off[SM_NENTRIES] = {")
    for i in range(0, len(ents), 12):
        o.append("\t" + ", ".join(str(e[1]) + "L" for e in ents[i:i + 12]) + ",")
    o.append("};")
    o.append("static const unsigned char sm_len[SM_NENTRIES] = {")
    for i in range(0, len(ents), 20):
        o.append("\t" + ", ".join(str(e[2]) for e in ents[i:i + 20]) + ",")
    o.append("};")
    o.append("")
    o.append("struct sm_authored { unsigned short off; unsigned char len;")
    o.append("                     const char *text; };")
    o.append("static const struct sm_authored sm_authored[SM_NAUTHORED] = {")
    for off, text in authored:
        esc = text.decode("latin-1").replace("\\", "\\\\").replace('"', '\\"')
        esc = esc.replace("\n", "\\n").replace("\r", "\\r")
        o.append(f'\t{{ {off}, {len(text)}, "{esc}" }},')
    o.append("};")
    o.append("")
    o.append("#endif /* STRS_MAP_DOS12_H */")

    out = os.path.abspath(args.out)
    with open(out, "w") as fh:
        fh.write("\n".join(o) + "\n")
    print(f"wrote {out}: {len(ents)} positions + {len(authored)} authored, "
          f"pool {doc['pool_size']} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
